### ISSUE TITLE
installing nfs ganesha does not work.

### ISSUE THREAD

**Issue by kristvanbesien** [gluster/gluster-ansible-features#48]
Given the following playbook:

```
- name: install ganesha
  hosts: ganesha
  become: true
  vars:
    gluster_features_ganesha_volume: vol1
    gluster_features_ganesha_hostnames: 
    - "{{ groups['ganesha'] }}"
    gluster_features_ganesha_haname: ganesha
    gluster_features_ganesha_viplis: "192.168.21.21,192.168.21.22"
    gluster_features_ganesha_clusternodes:
    - "{{ groups['ganesha'] }}"
    gluster_features_ganesha_masternode: "{{ groups['ganesha'][0] }}"

  roles:
  - gluster.features
  ```

This fails at the "Copy the ssh keys to the local machine" task.

The reason is that it attempts to do this before those keys have been generated.
